spring:
  application:
    name: backend-api

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

server:
  port: 8081

service:
  ai:
    url: http://localhost:8082
    secret-key: ${AI_SECRET_KEY}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 900000
      refresh-expiration: 900000
